const REPO="neophilism/End-To-End-Everywhere-Security-Architecture-Standard";
const BASE="https://github.com/"+REPO+"/blob/main/";
const state={data:null,view:"home",filter:"all",selected:[],query:"",role:"product"};
const $=id=>document.getElementById(id);
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const cap=s=>String(s).replace(/[-_]/g," ").replace(/\b\w/g,c=>c.toUpperCase());
const link=(view,more="")=>"?view="+encodeURIComponent(view)+(more?"&"+more:"");
const status=p=>["experimental","provisional","deprecated","legacy","prohibited"].includes(p.status)?"warning":"";
const FALLBACK={standard:"Source unavailable",source:"Repository-linked edition",families:[],profiles:[],specifications:[]};
let catalog=FALLBACK;
function getRoute(){const p=new URLSearchParams(location.search);return{view:p.get("view")||"home",id:p.get("id")||""}}
function go(view,id=""){history.pushState({},"",link(view,id?"id="+encodeURIComponent(id):""));render();window.scrollTo({top:0,behavior:"instant"})}
const navigate=(event)=>{const a=event.target.closest("a[data-route]");if(!a)return;event.preventDefault();go(a.dataset.route,a.dataset.id||"")};
document.addEventListener("click",navigate);
window.addEventListener("popstate",()=>render());
const page=(html)=>{$("app").innerHTML=html;};
function heroArt(){return '<div class="hero-art" aria-label="Interconnected secure layers illustration" role="img"><svg viewBox="0 0 460 400" aria-hidden="true"><defs><linearGradient id="g" x1="0" y1="0" x2="1" y2="1"><stop stop-color="#e4f7dd"/><stop offset="1" stop-color="#b9e5c9"/></linearGradient></defs><g fill="none" stroke="#b3d2c2" stroke-width="1.2"><circle cx="233" cy="195" r="148" stroke-dasharray="4 9"/><circle cx="233" cy="195" r="109"/><circle cx="233" cy="195" r="66" stroke-dasharray="4 7"/><path d="M60 140L233 195 370 87M233 195L395 285M233 195L104 310"/></g><g fill="#d0e8d3" stroke="#a6cbbb"><circle cx="60" cy="140" r="8"/><circle cx="370" cy="87" r="8"/><circle cx="395" cy="285" r="7"/><circle cx="104" cy="310" r="8"/></g><rect x="149" y="113" width="169" height="169" rx="37" fill="url(#g)" stroke="#97c8ad"/><rect x="167" y="132" width="133" height="132" rx="29" fill="#e8f8e5" stroke="#accfb8"/><rect x="189" y="168" width="90" height="79" rx="18" fill="#226a56"/><path d="M207 170v-18a27 27 0 0 1 54 0v18" stroke="#226a56" stroke-width="12" fill="none" stroke-linecap="round"/><circle cx="234" cy="200" r="10" fill="#d5f5bd"/><path d="M234 208v14" stroke="#d5f5bd" stroke-width="6" stroke-linecap="round"/><g fill="#397964"><circle cx="233" cy="48" r="6"/><circle cx="83" cy="200" r="5"/><circle cx="386" cy="207" r="6"/><circle cx="232" cy="348" r="5"/></g></svg><div class="art-label">✦ BUILT AROUND TRUST</div></div>'}
function home(){const cards=[["◈","For leaders","Understand the choices, risks, and responsibilities in everyday language.","guide"],["▦","Explore the profiles","Compare available approaches for encryption, identity, privacy, and more.","profiles"],["≡","The full reference","Find authoritative specifications, security requirements, and source material.","library"]];return '<section class="hero"><div><div class="eyebrow">AN OPEN STANDARD FOR A SAFER DIGITAL WORLD</div><h1>Security for<br>everyone.<br><em>Not just experts.</em></h1><p>End-to-end encryption protects what matters. Understanding it should not be complicated. Explore a clear, practical guide to the choices behind secure digital products — from first principles to technical detail.</p><div class="buttons"><a class="btn" href="'+link("guide")+'" data-route="guide">Find the right approach <span>↗</span></a><a class="btn secondary" href="'+link("profiles")+'" data-route="profiles">Explore the standard <span>→</span></a></div></div>'+heroArt()+'</section><div class="metric-strip"><div class="metric"><b>'+catalog.families.length+'</b><span>Areas of architecture</span></div><div class="metric"><b>'+catalog.profiles.length+'</b><span>Versioned profiles</span></div><div class="metric"><b>'+catalog.specifications.length+'</b><span>Specification documents</span></div></div><section><div class="section-header"><div><div class="eyebrow">FIND YOUR STARTING POINT</div><h2>There is a place for you here.</h2><p>Different responsibilities. One understandable standard.</p></div></div><div class="card-grid">'+cards.map(c=>'<a class="feature-card" href="'+link(c[3])+'" data-route="'+c[3]+'"><span class="feature-icon">'+c[0]+'</span><h3>'+c[1]+'</h3><p>'+c[2]+'</p><div class="card-bottom"><span>Explore</span><span>↗</span></div></a>').join("")+'</div></section><section class="dark-banner"><div><div class="eyebrow" style="color:#c8e7ac">FROM PRINCIPLE TO PRACTICE</div><h2>One source of truth. Many ways to learn.</h2><p>All profiles and specifications on this site come from the public source repository. Browse the human-friendly view, then inspect the exact authoritative source when needed.</p></div><a class="btn" href="'+link("about")+'" data-route="about">How it works ↗</a></section>'}
function intro(eye,title,desc){return '<div class="page-intro"><div class="eyebrow">'+esc(eye)+'</div><h1>'+esc(title)+'</h1><p>'+esc(desc)+'</p></div>'}
const choices=[["messages","Private messaging","pairwise-e2ee","group-e2ee","identity-architecture","key-verification"],["files","File sharing","attachment-encryption","secret-storage","backup-recovery"],["calls","Voice and video","real-time-media","identity-architecture","transport-security"],["privacy","Hide unnecessary metadata","metadata-privacy","contact-discovery","telemetry"],["platform","Platform-wide foundations","client-security","server-trust","secure-development","software-supply-chain"],["assurance","Evaluate security claims","security-verification","assurance-level","formal-verification","vulnerability-disclosure"]];
function guide(){const selected=new Set(state.selected);return intro("A PRACTICAL START","What are you building?","Choose the capabilities that matter to your product. We'll show you the relevant sections to explore. This is learning guidance, not an automatic certification or compliant configuration.")+'<div class="detail-panel"><h2>Start with your needs</h2><p>You can select several. Every project also needs a clear threat model, authenticated identities, explicit security properties, and appropriate key management.</p><div class="checklist">'+choices.map(c=>'<label><input type="checkbox" data-choice="'+c[0]+'" '+(selected.has(c[0])?"checked":"")+'> <span><strong>'+c[1]+'</strong></span></label>').join("")+'</div><div id="guide-result" class="result-box" aria-live="polite"></div></div>'}
function guideResult(){const ids=[...new Set(choices.filter(c=>state.selected.includes(c[0])).flatMap(c=>c.slice(2)))];const target=$("guide-result");if(!target)return;target.innerHTML='<h3>'+(!ids.length?"Choose a capability to begin":"Start exploring "+ids.length+" relevant areas")+'</h3><p>'+(!ids.length?"Your tailored exploration path will appear here.":"These topics help frame your design, but choosing profiles requires exact versioning, compatibility checks, and implementation evidence.")+'</p>'+(ids.length?'<div class="filter-bar">'+ids.map(id=>{const f=catalog.families.find(x=>x.family_id===id);return '<a class="filter-btn" href="'+link("profiles","family="+encodeURIComponent(id))+'">'+esc(f?.name||cap(id))+' ↗</a>'}).join("")+'</div>':'')+'<p><a class="text-link" href="'+BASE+'spec/threat-model.md" target="_blank" rel="noopener noreferrer">Start with the threat model ↗</a></p>'}
function profiles(){const param=new URLSearchParams(location.search).get("family");if(param&&catalog.families.some(f=>f.family_id===param))state.filter=param;const families=[{family_id:"all",name:"All areas"},...catalog.families.filter(f=>!f.family_id.startsWith("example"))];const visible=catalog.profiles.filter(p=>(state.filter==="all"||p.family_id===state.filter)&&!p.family_id.startsWith("example")&&p.family_id!=="foundation");return intro("EXPLORE ARCHITECTURE","Explore the profiles.","Instead of forcing one design on every product, the standard documents different defensible architectural choices. Compare options, constraints, and exact source material.")+'<div class="filter-bar">'+families.map(f=>'<button type="button" class="filter-btn '+(state.filter===f.family_id?"active":"")+'" data-family="'+esc(f.family_id)+'">'+esc(f.name)+'</button>').join("")+'</div><div class="section-header"><h2>'+visible.length+' profiles</h2><span class="small-label">EXACT VERSIONS • SOURCE LINKED</span></div><div class="profile-grid">'+(visible.length?visible.map(p=>'<a class="profile-card" href="'+link("profile","id="+encodeURIComponent(p.profile_id+"@"+p.profile_version))+'" data-route="profile" data-id="'+esc(p.profile_id+"@"+p.profile_version)+'"><span class="pill '+status(p)+'">'+esc(p.status)+'</span><small>'+esc(catalog.families.find(f=>f.family_id===p.family_id)?.name||cap(p.family_id))+'</small><h3>'+esc(cap(p.profile_id))+'</h3><p>'+esc(p.notes||"Explore this profile in the standard.")+'</p><div class="card-bottom"><span>v'+esc(p.profile_version)+'</span><span>View details ↗</span></div></a>').join(""):'<div class="empty-state">No profiles currently in this family.</div>')+'</div><p class="note">A profile marked "recommended" is a catalog classification, not a certification of a product. Experimental or provisional options are not production recommendations. Illustrative fixtures are kept in a separate development catalog and do not supply production security properties.</p>'}
function profile(id){const p=catalog.profiles.find(x=>x.profile_id+"@"+x.profile_version===id);if(!p)return intro("NOT FOUND","Profile not found","Return to Explore profiles and select another entry.")+'<a class="btn" href="'+link("profiles")+'" data-route="profiles">Browse profiles</a>';const f=catalog.families.find(x=>x.family_id===p.family_id);const related=catalog.specifications.filter(s=>s.path.includes(p.family_id)||s.path.includes(p.family_id.replace("attachment-encryption","attachments-file-encryption"))).slice(0,3);return intro(f?.name||"Architecture profile",cap(p.profile_id),"Version "+p.profile_version+" · "+p.status)+'<div class="detail-panel"><span class="pill '+status(p)+'">'+esc(p.status)+'</span><h2>What this approach means</h2><p>'+esc(p.notes||f?.description||"See the authoritative source for detailed requirements.")+'</p><div class="facts"><div class="fact"><small>EXACT PROFILE REFERENCE</small><strong>'+esc(id)+'</strong></div><div class="fact"><small>PROFILE FAMILY</small><strong>'+esc(f?.name||p.family_id)+'</strong></div><div class="fact"><small>ARCHITECTURAL CHOICE RULE</small><strong>'+esc(f?.cardinality||"See family rules")+'</strong></div><div class="fact"><small>LIFECYCLE</small><strong>'+esc(p.status)+'</strong></div></div><div class="small-label">Security properties referenced</div><p>'+esc((p.security_properties||[]).join(" · ")||"See normative security properties")+'</p><div class="small-label">Requirements and incompatibilities</div><p>Requires: '+esc((p.requires_profile_refs||[]).join(", ")||"None declared")+'</p><p>Incompatible with: '+esc((p.incompatible_profile_refs||[]).join(", ")||"None declared")+'</p><div class="buttons"><a class="btn" href="'+BASE+'profiles/catalog.json" target="_blank" rel="noopener noreferrer">View authoritative catalog ↗</a>'+(related[0]?'<a class="btn secondary" href="'+BASE+encodeURI(related[0].path)+'" target="_blank" rel="noopener noreferrer">Read related specification →</a>':'')+'</div><p class="note">This is a readable view of repository data, not a substitute for profile resolution, implementation assurance, or the normative documents.</p></div>'}
function library(){const docs=catalog.specifications;return intro("ORIGINAL SOURCE MATERIAL","The standards library.","Explore normative requirements, implementation guidance, and technical reference documents. Each document opens directly at its authoritative repository location.")+'<div class="doc-list">'+docs.map(d=>'<a class="doc-card" href="'+BASE+encodeURI(d.path)+'" target="_blank" rel="noopener noreferrer"><small>'+esc(d.path)+'</small><h3>'+esc(d.title)+'</h3><p>Read the current source document and its complete requirements.</p><div class="card-bottom"><span>Read on GitHub</span><span>↗</span></div></a>').join("")+'</div>'}
function about(){return intro("OUR APPROACH","One standard. Clearly explained.","This website is a navigational and educational layer over the authoritative open repository. It should make the standard approachable without oversimplifying security claims.")+'<div class="card-grid"><div class="feature-card"><span class="feature-icon">①</span><h3>Written in the open</h3><p>Specification files, versioned profiles, and machine-readable registers live in GitHub.</p></div><div class="feature-card"><span class="feature-icon">②</span><h3>Built automatically</h3><p>Publication builds read the repository files instead of keeping a separate manually maintained content database.</p></div><div class="feature-card"><span class="feature-icon">③</span><h3>Always traceable</h3><p>Every detailed profile and library entry has a link to its authoritative source.</p></div></div><div class="detail-panel" style="margin-top:26px"><h2>Important distinctions</h2><p>The portal explains development toward the corrected E2EESA candidate. The original rc.1 is archived; independent expert review remains pending. No profile listing, configuration exploration, or site content constitutes certification or implementation approval.</p><p>For every actual security claim, verify the exact standard version, selected profile versions, declared threats and assumptions, compatibility resolution, and assurance evidence.</p><div class="buttons"><a class="btn" href="'+BASE+'README.md" target="_blank" rel="noopener noreferrer">Read project status ↗</a><a class="btn secondary" href="'+link("library")+'" data-route="library">Browse source library →</a></div></div>'}
function render(){const {view,id}=getRoute();state.view=view;const viewLabels={home:"Overview",guide:"Find your path",profiles:"Profiles",profile:"Profile details",library:"Standards library",about:"About the standard"};document.querySelectorAll("[data-nav]").forEach(el=>el.classList.toggle("active",el.dataset.nav===(view==="profile"?"profiles":view)));$("breadcrumb-label").textContent=(viewLabels[view]||"Overview").toUpperCase();const views={home,guide,profiles,library,about};page(view==="profile"?profile(id):(views[view]||home)());if(view==="guide")guideResult();document.querySelector(".sidebar").classList.remove("open");$("menu-button").setAttribute("aria-expanded","false")}
document.addEventListener("change",event=>{if(event.target.matches("[data-choice]")){const id=event.target.dataset.choice;state.selected=event.target.checked?[...new Set([...state.selected,id])]:state.selected.filter(x=>x!==id);guideResult()}});
document.addEventListener("click",event=>{const b=event.target.closest("[data-family]");if(b){state.filter=b.dataset.family;history.replaceState({},"",link("profiles"));render()}});
$("menu-button").addEventListener("click",()=>{const open=document.querySelector(".sidebar").classList.toggle("open");$("menu-button").setAttribute("aria-expanded",String(open))});
const search=$("site-search");
const sourceItems=()=>[...catalog.families.filter(f=>!f.family_id.startsWith("example")).map(f=>({title:f.name,desc:f.description,view:"profiles",family:f.family_id})),...catalog.profiles.filter(p=>!p.family_id.startsWith("example")).map(p=>({title:cap(p.profile_id),desc:p.notes||"",view:"profile",id:p.profile_id+"@"+p.profile_version})),...catalog.specifications.map(d=>({title:d.title,desc:d.path,url:BASE+encodeURI(d.path)}))];
function searchUpdate(){const q=search.value.trim().toLowerCase();const results=$("search-results");if(!q){results.hidden=true;search.setAttribute("aria-expanded","false");return}const found=sourceItems().filter(o=>(o.title+" "+o.desc).toLowerCase().includes(q)).slice(0,9);results.innerHTML=found.length?found.map(o=>'<a class="search-hit" '+(o.url?'href="'+o.url+'" target="_blank" rel="noopener noreferrer"':'href="'+link(o.view,o.id?"id="+encodeURIComponent(o.id):o.family?"family="+encodeURIComponent(o.family):"")+'" data-route="'+o.view+'"'+(o.id?' data-id="'+esc(o.id)+'"':""))+'><b>'+esc(o.title)+'</b><small>'+esc(o.desc.slice(0,95))+'</small></a>').join(""):'<div class="empty-state">No matching entries. Try a broader term.</div>';results.hidden=false;search.setAttribute("aria-expanded","true")}
search.addEventListener("input",searchUpdate);
search.addEventListener("keydown",e=>{if(e.key==="Escape"){search.value="";searchUpdate();search.blur()}if(e.key==="Enter"){const a=$("search-results").querySelector("a");if(a)a.click()}});
document.addEventListener("keydown",e=>{if(e.key==="/"&&!["INPUT","TEXTAREA"].includes(document.activeElement.tagName)){e.preventDefault();search.focus()}});
document.addEventListener("click",e=>{if(!e.target.closest(".search-wrap")){$("search-results").hidden=true;search.setAttribute("aria-expanded","false")}});
async function init(){try{const res=await fetch("./data/standard.json",{cache:"no-store"});if(!res.ok)throw Error("No built content");catalog=await res.json();if(!Array.isArray(catalog.profiles)||!Array.isArray(catalog.specifications))throw Error("Invalid generated catalog");$("source-version").textContent="Source: GitHub · "+esc(catalog.standard||"release candidate")+(catalog.commit?" · "+catalog.commit.slice(0,8):"")}catch(err){console.error("Unable to load generated standards data",err);page(intro("SOURCE UNAVAILABLE","Standards data not available","The generated content file is missing or unavailable. Browse the authoritative repository directly.")+'<a class="btn" href="https://github.com/'+REPO+'">Open GitHub ↗</a>');return}render()}
init();